name: chart-logstash pipeline
trigger:
  - master
pr: none
resources:
  repositories:
  - repository: charts
    type: github
    name: hmcts/charts
    endpoint: 'hmcts'

variables:
  chartName: logstash
  chartReleaseName: chart-logstash-ci
  chartNamespace: chart-tests
  acrName: "hmctspublic"
  helmDeleteWait: "300"
  helmInstallWait: "300"
  serviceConnection: "DCD-CFTAPPS-SBOX"
  registryServiceConnection: "azurerm-prod"
  aksResourceGroup: "sbox-01-rg"
  aksCluster: "sbox-01-aks"
  helmVersion: "2.11.0"

steps:
  - task: HelmInstaller@0
    inputs:
      helmVersion: $(helmVersion)
      checkLatestHelmVersion: false
      installKubectl: false

  - task: AzureCLI@1
    displayName: "AKS Authenticate"
    inputs:
      azureSubscription: $(serviceConnection)
      scriptLocation: "inlineScript"
      inlineScript: az aks get-credentials --admin --resource-group $(aksResourceGroup) --name $(aksCluster)

  - task: AzureCLI@1
    displayName: "Add custom charts repo"
    inputs:
      azureSubscription: $(registryServiceConnection)
      scriptLocation: "inlineScript"
      inlineScript: az acr helm repo add --name $(acrName)

  - script: helm dependency update stable/$(chartName)
    displayName: "Retrieve helm dependencies (if any)"

  - script: helm package stable/$(chartName)
    displayName: "Helm Package"

  - task: AzureCLI@1
    displayName: "Helm Publish"
    inputs:
      azureSubscription: $(registryServiceConnection)
      scriptLocation: "inlineScript"
      inlineScript: |
        CHART_FILE=$(ls $(chartName)-[0-9]*)
        az acr helm push --name $(acrName) $CHART_FILE
