apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fluxcloud.fullname" . }}
  labels:
    app: {{ template "fluxcloud.name" . }}
    chart: {{ template "fluxcloud.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "fluxcloud.name" . }}
      release: {{ .Release.Name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ template "fluxcloud.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: fluxcloud
        image: "{{ .Values.imageRepository }}:{{ .Values.imageTag }}"
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.serviceTargetPort }}
        {{- if or .Values.extraEnvs .Values.secretEnvs }}
        env:
          {{- if .Values.extraEnvs }}
{{ toYaml .Values.extraEnvs | indent 8 }}
          {{- end }}
          {{- if .Values.secretEnvs }}
{{ toYaml .Values.secretEnvs | indent 8 }}
          {{- end }}
        {{- end }}
